Repository pyro-ppl/funsor, pull requests merged in 2019-10, with the labels that each got.

#263 Add MultivariateNormal pattern for Binary to cover matmul
  funsor/distributions.py
  test/test_distributions.py
Labels: awaiting review

#262 Add adjoint patterns for substitution into discrete inputs of gaussians
  funsor/adjoint.py
  funsor/gaussian.py
  funsor/torch.py
  test/test_adjoint.py
Labels: awaiting review

#266 Add test of pyro-api
  .travis.yml
  funsor/ops.py
  setup.cfg
  test/pyroapi/conftest.py
  test/pyroapi/test_pyroapi.py
Labels: awaiting review, discussion

#265 Refactor to reduce size of stack traces for debugging
  funsor/cnf.py
  funsor/integrate.py
  funsor/interpreter.py
  funsor/montecarlo.py
  funsor/optimizer.py
  funsor/registry.py
  funsor/terms.py
Labels: awaiting review, refactor

#267 Add pyroapi requirement to setup.py
  .travis.yml
  setup.py
Labels: awaiting review, easy

#268 Add Gamma and VonMises distributions
  funsor/distributions.py
  test/test_distributions.py
Labels: awaiting review, easy

#246 bias estimation experiment
  .gitignore
  Makefile
  examples/sensor.py
Labels: awaiting review

#261 Add mixed-effect HMM example on harbour seal data
  Makefile
  examples/mixed_hmm/README.md
  examples/mixed_hmm/__init__.py
  examples/mixed_hmm/experiment.py
  examples/mixed_hmm/model.py
  examples/mixed_hmm/seal_data.py
  setup.py
Labels: awaiting review, examples

#270 Add zeros, ones, randn to funsor.compat.ops
  funsor/compat/__init__.py
  funsor/compat/ops.py
  funsor/ops.py
Labels: awaiting review

#269 Add seed handler and tests
  funsor/minipyro.py
  test/test_minipyro.py
Labels: awaiting review

#271 Add PatternMissingError and use it for more informative failures in SVI
  funsor/interpreter.py
  funsor/minipyro.py
  funsor/numpy.py
  funsor/terms.py
  funsor/torch.py
Labels: awaiting review

#272 Add ops.allclose to funsor.compat.ops
  funsor/compat/ops.py
  funsor/testing.py
  test/test_minipyro.py
Labels: awaiting review

#274 Fix lint error due to merge conflict
  test/test_minipyro.py
Labels: awaiting review, easy

#276 Accept more types to .reduce(), .sample(), Integrate()
  examples/vae.py
  funsor/integrate.py
  funsor/terms.py
  test/examples/test_bart.py
  test/test_gaussian.py
  test/test_integrate.py
  test/test_joint.py
  test/test_terms.py
Labels: awaiting review

#277 Add docstrings for funsor.pyro.hmm classes
  docs/source/conf.py
  funsor/pyro/hmm.py
Labels: awaiting review, easy

#278 Remove incomplete SSVAE example
  examples/ss_vae_delayed.py
Labels: awaiting review, easy, examples

#279 Fix dependent type inference in funsor.torch.arange
  funsor/torch.py
  test/test_torch.py
Labels: awaiting review

#280 Add Funsor docstrings
  docs/source/funsors.rst
  docs/source/ops.rst
  funsor/distributions.py
  funsor/numpy.py
  funsor/ops.py
  funsor/terms.py
  funsor/torch.py
Labels: awaiting review

#282 Implement sound is_affine() test
  funsor/affine.py
  funsor/cnf.py
  funsor/distributions.py
  funsor/domains.py
  test/test_affine.py
Labels: awaiting review

#283 Update readme
  README.md
  docs/source/index.rst
Labels: awaiting review

#281 Implement eager contract (Tensor,Tensor) via einsum
  funsor/cnf.py
  funsor/sum_product.py
  test/test_cnf.py
Labels: awaiting review

#284 Refactor towards Gaussian._eager_subs_affine()
  docs/source/affine.rst
  docs/source/funsors.rst
  docs/source/index.rst
  funsor/affine.py
  funsor/cnf.py
  funsor/gaussian.py
Labels: awaiting review, refactor

#285 Implement affine pattern recognition for Gaussian substitution
  funsor/gaussian.py
  test/test_gaussian.py
Labels: awaiting review

#286 Affine gaussian 3
  funsor/distributions.py
  funsor/torch.py
  test/examples/test_sensor_fusion.py
  test/pyro/test_convert.py
Labels: awaiting review, refactor

#288 Fix distributions.Gamma docstring
  funsor/distributions.py
Labels: awaiting review, easy

#287 Bump to version 0.1.0 and prepare for release
  .gitignore
  .travis.yml
  README.md
  docs/requirements.txt
  examples/eeg_slds.py
  examples/mixed_hmm/experiment.py
  examples/mixed_hmm/model.py
  examples/mixed_hmm/seal_data.py
  funsor/adjoint.py
  funsor/einsum.py
  funsor/interpreter.py
  funsor/memoize.py
  funsor/montecarlo.py
  funsor/torch.py
  setup.py
  test/test_adjoint.py
  test/test_joint.py
  test/test_memoize.py
  test/test_optimizer.py
  test/test_torch.py
Labels: awaiting review

#289 Bump version to 0.1.1
  setup.py
Labels: awaiting review

#290 Add pytest as core dependency
  setup.py
Labels: awaiting review, easy

#291 Link to arxiv paper in readme
  README.md
Labels: awaiting review, easy
