Repository pyro-ppl/funsor, pull requests merged in 2019-04, with the labels that each got.

#97 Add Lambda and Independent funsors
  funsor/__init__.py
  funsor/delta.py
  funsor/joint.py
  funsor/terms.py
  funsor/torch.py
  test/test_distributions.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review

#95 Add a VAE example using the monte_carlo interpretation
  Makefile
  examples/discrete_hmm.py
  examples/kalman_filter.py
  examples/minipyro.py
  examples/vae.py
  funsor/distributions.py
  funsor/gaussian.py
  funsor/joint.py
  funsor/montecarlo.py
  funsor/terms.py
  funsor/torch.py
  setup.py
  test/test_terms.py
Labels: awaiting review, examples

#114 Add initial sphinx docs
  Makefile
  docs/Makefile
  docs/make.bat
  docs/source/adjoint.rst
  docs/source/conf.py
  docs/source/distributions.rst
  docs/source/domains.rst
  docs/source/einsum.rst
  docs/source/funsors.rst
  docs/source/index.rst
  docs/source/interpretations.rst
  docs/source/minipyro.rst
  docs/source/ops.rst
  docs/source/optimizer.rst
  funsor/gaussian.py
  funsor/interpreter.py
  funsor/numpy.py
  funsor/terms.py
  funsor/torch.py
  setup.py
Labels: awaiting review, easy

#115 Add moment_matching interpretation + SLDS example
  Makefile
  examples/kalman_filter.py
  examples/slds.py
  funsor/delta.py
  funsor/gaussian.py
  funsor/joint.py
  funsor/terms.py
  test/test_joint.py
Labels: awaiting review

#117 Add a torch_tensordot operation
  funsor/joint.py
  funsor/numpy.py
  funsor/torch.py
  test/test_torch.py
Labels: awaiting review, easy

#118 Support wrapping PyTorch builtin functions
  funsor/six.py
  test/test_torch.py
Labels: awaiting review, easy

#116 Add an Affine term to represent multilinear functions of real Variables
  docs/source/conf.py
  funsor/__init__.py
  funsor/affine.py
  funsor/montecarlo.py
  test/test_affine.py
  test/test_pattern.py
Labels: awaiting review

#119 Add rule for creating Gaussians from Affine inputs
  examples/kalman_filter.py
  funsor/affine.py
  funsor/distributions.py
  funsor/gaussian.py
  funsor/torch.py
  test/test_distributions.py
  test/test_gaussian.py
Labels: awaiting review

#120 Add Beta, Dirichlet, and Binomial distributions
  funsor/distributions.py
  funsor/torch.py
  test/test_distributions.py
  test/test_torch.py
Labels: awaiting review

#125 Reinstate examples/minipyro.py, forked from pyro/examples
  Makefile
  examples/kalman_filter.py
  examples/minipyro.py
  examples/slds.py
  funsor/joint.py
  funsor/minipyro.py
  funsor/optimizer.py
  funsor/sum_product.py
  test/test_gaussian.py
Labels: awaiting review, examples

#128 Support constraints in funsor.minipyro
  funsor/minipyro.py
  test/test_minipyro.py
Labels: awaiting review

#129 Remove dependency on pyro ParamStoreDict
  examples/minipyro.py
  funsor/minipyro.py
  test/test_minipyro.py
Labels: awaiting review

#133 Add JitTrace_ELBO class to minipyro
  Makefile
  docs/source/conf.py
  examples/minipyro.py
  funsor/distributions.py
  funsor/domains.py
  funsor/gaussian.py
  funsor/minipyro.py
  funsor/torch.py
  setup.py
  test/test_gaussian.py
  test/test_minipyro.py
Labels: awaiting review

#134 Avoid legacy constructors
  funsor/distributions.py
  funsor/gaussian.py
  funsor/minipyro.py
Labels: awaiting review, refactor
