Repository pyro-ppl/funsor, pull requests merged in 2019-09, with the labels that each got.

#208 Add ClippedAdam to funsor.minipyro
  funsor/minipyro.py
  test/test_minipyro.py
Labels: awaiting review

#209 Add a Poisson distribution
  funsor/distributions.py
  test/test_distributions.py
Labels: awaiting review

#206 Implement Cat funsor
  examples/pcfg.py
  funsor/__init__.py
  funsor/joint.py
  funsor/sum_product.py
  funsor/terms.py
  funsor/torch.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review

#210 Add sigmoid op
  funsor/ops.py
  funsor/terms.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review, easy

#212 Add parametric types for more convenient pattern matching
  funsor/__init__.py
  funsor/adjoint.py
  funsor/pattern.py
  funsor/registry.py
  funsor/terms.py
  setup.py
  test/test_pattern.py
  test/test_terms.py
Labels: awaiting review

#216 Add a .classname attribute
  funsor/interpreter.py
  funsor/terms.py
  test/test_terms.py
Labels: awaiting review

#217 Support Independent(Normal) in matrix_and_mvn_to_funsor()
  docs/source/pyro.rst
  funsor/pyro/convert.py
  test/pyro/test_convert.py
Labels: awaiting review

#213 add complete slds example using eeg data
  Makefile
  examples/eeg_slds.py
Labels: awaiting review

#218 Support set-valued args to Funsor.reduce()
  examples/slds.py
  examples/vae.py
  funsor/terms.py
  test/test_terms.py
Labels: awaiting review

#219 Make .pretty() more terse for large expressions
  funsor/terms.py
Labels: awaiting review

#221 Add eager_or_die interpretation to diagnose missing patterns
  funsor/terms.py
  test/test_terms.py
Labels: awaiting review, discussion

#222 Add support for nested union types
  funsor/terms.py
  test/test_terms.py
Labels: awaiting review

#225 Fix expand bugs in AffineNormal patterns
  funsor/pyro/convert.py
  test/pyro/test_convert.py
Labels: awaiting review

#227 Refactor alpha conversion logic to allow overloads
  funsor/adjoint.py
  funsor/contract.py
  funsor/integrate.py
  funsor/terms.py
Labels: awaiting review, refactor

#229 Add eager pattern for homogeneous Stack(Tensor)
  funsor/terms.py
  funsor/torch.py
  test/test_torch.py
Labels: awaiting review

#226 Make Independent into a three-parameter funsor
  examples/vae.py
  funsor/delta.py
  funsor/joint.py
  funsor/pyro/convert.py
  funsor/terms.py
  test/test_alpha_conversion.py
  test/test_distributions.py
  test/test_terms.py
Labels: awaiting review

#230 Implement substitution into Slice funsors
  funsor/pyro/convert.py
  funsor/terms.py
  test/test_terms.py
Labels: awaiting review

#231 Support gradient in cholesky_inverse()
  funsor/gaussian.py
  test/test_gaussian.py
Labels: awaiting review, easy

#232 Fix alpha conversion bugs in Subs, Cat, Slice
  funsor/joint.py
  funsor/terms.py
  funsor/torch.py
  test/test_alpha_conversion.py
Labels: awaiting review, bug

#240 Include reinterpret() in debug logging
  funsor/interpreter.py
Labels: awaiting review, testing

#157 Add a single normal form for sum-product contractions
  funsor/__init__.py
  funsor/adjoint.py
  funsor/affine.py
  funsor/cnf.py
  funsor/contract.py
  funsor/delta.py
  funsor/distributions.py
  funsor/einsum.py
  funsor/gaussian.py
  funsor/integrate.py
  funsor/joint.py
  funsor/minipyro.py
  funsor/montecarlo.py
  funsor/ops.py
  funsor/optimizer.py
  funsor/pyro/convert.py
  funsor/pyro/distribution.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch.py
  test/pyro/test_convert.py
  test/test_adjoint.py
  test/test_affine.py
  test/test_alpha_conversion.py
  test/test_cnf.py
  test/test_contract.py
  test/test_distributions.py
  test/test_gaussian.py
  test/test_joint.py
  test/test_minipyro.py
  test/test_numpy.py
  test/test_optimizer.py
  test/test_samplers.py
  test/test_sum_product.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review, refactor

#242 Fix renaming of int variable in Gaussian
  funsor/gaussian.py
  test/test_gaussian.py
Labels: awaiting review, easy

#244 Add xfailing test for BART analytic kls
  funsor/cnf.py
  test/examples/test_bart.py
Labels: awaiting review, easy

#247 Add minimal failing tests for sensor fusion example
  test/examples/test_sensor_fusion.py
Labels: awaiting review, testing

#248 Implement ReshapeOp, .shape attribute and .reshape() method
  funsor/domains.py
  funsor/ops.py
  funsor/terms.py
  funsor/torch.py
  test/test_torch.py
Labels: awaiting review

#249 Implement affine funsor approximation
  funsor/__init__.py
  funsor/affine.py
  funsor/torch.py
  test/test_affine.py
  test/test_torch.py
Labels: awaiting review

#250 Implement ops.matmul and align_tensors(..., expand=True)
  funsor/distributions.py
  funsor/domains.py
  funsor/ops.py
  funsor/pyro/convert.py
  funsor/terms.py
  funsor/torch.py
  test/test_torch.py
Labels: awaiting review

#245 Add pattern for MultivariateNormal(affine)
  funsor/affine.py
  funsor/distributions.py
  funsor/ops.py
  funsor/torch.py
  test/examples/test_sensor_fusion.py
  test/test_affine.py
  test/test_distributions.py
Labels: awaiting review

#251 Ensure all funsor.* modules are imported in funsor/__init__.py
  funsor/__init__.py
  test/test_import.py
Labels: awaiting review, easy

#252 Fix strategy of gaussian mixture .unscaled_sample()
  funsor/cnf.py
  funsor/gaussian.py
  test/test_samplers.py
Labels: awaiting review

#256 Move all integrate patterns into integrate.py
  funsor/delta.py
  funsor/gaussian.py
  funsor/integrate.py
  funsor/joint.py
Labels: awaiting review, easy

#257 Fix Integrate._alpha_convert() by invoking to_funsor()
  funsor/integrate.py
  test/test_integrate.py
Labels: awaiting review, easy

#255 Implement a MarkovProduct funsor
  docs/source/funsors.rst
  funsor/__init__.py
  funsor/pyro/distribution.py
  funsor/pyro/hmm.py
  funsor/sum_product.py
  funsor/torch.py
  test/examples/test_bart.py
  test/pyro/test_hmm.py
  test/test_sum_product.py
Labels: awaiting review

#258 Dispatch to either torch.cholesky() or torch.sqrt()
  funsor/gaussian.py
  funsor/joint.py
  funsor/pyro/convert.py
Labels: awaiting review, easy

#260 fix broken docs
  docs/requirements.txt
Labels: awaiting review

#259 Add adjoint methods to support backwards marginal through MarkovProduct
  funsor/adjoint.py
  funsor/registry.py
  test/test_adjoint.py
Labels: awaiting review
