Repository pyro-ppl/funsor, pull requests merged in 2019-02, with the labels that each got.

#17 Refactor according to v2 design doc
  README.md
  examples/kalman_filter.py
  examples/ss_vae_delayed.py
  funsor/__init__.py
  funsor/adjoint.py
  funsor/contract.py
  funsor/distributions.py
  funsor/domains.py
  funsor/engine/__init__.py
  funsor/engine/contract_engine.py
  funsor/engine/interpreter.py
  funsor/engine/materialize.py
  funsor/engine/tree_engine.py
  funsor/handlers.py
  funsor/interpreter.py
  funsor/minipyro.py
  funsor/pattern.py
  funsor/registry.py
  funsor/six.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch.py
  funsor/util.py
  test/test_adjoint.py
  test/test_contracy.py
  test/test_distributions.py
  test/test_engine.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review

#20 Add xfailing discrete hmm example
  Makefile
  examples/discrete_hmm.py
Labels: awaiting review, examples

#21 Fix Function, Substitute, Reduce; add more tests
  funsor/domains.py
  funsor/terms.py
  funsor/torch.py
  setup.cfg
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review

#22 Implement Stack funsor
  funsor/terms.py
  funsor/torch.py
  test/test_terms.py
Labels: awaiting review

#24 Fix normal distribution
  funsor/__init__.py
  funsor/distributions.py
  funsor/terms.py
  test/test_distributions.py
Labels: awaiting review

#25 Implement eager_categorical and add ops.getitem
  funsor/distributions.py
  funsor/domains.py
  funsor/ops.py
  funsor/terms.py
  funsor/torch.py
  test/test_distributions.py
Labels: awaiting review

#29 Drop Substitute funsor; close Function under substitution
  funsor/distributions.py
  funsor/terms.py
  funsor/torch.py
  test/test_torch.py
Labels: awaiting review, refactor

#23 Add naive einsum implementation and tests
  test/test_einsum.py
Labels: awaiting review

#33 Implement advanced indexing for Tensor
  funsor/__init__.py
  funsor/domains.py
  funsor/testing.py
  funsor/torch.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review

#34 Fix Categorical distribution and getitem op
  funsor/torch.py
  test/test_distributions.py
Labels: awaiting review

#35 Drop support for int array domains; rename ints() -> bint()
  examples/discrete_hmm.py
  examples/ss_vae_delayed.py
  funsor/__init__.py
  funsor/distributions.py
  funsor/domains.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch.py
  test/test_distributions.py
  test/test_einsum.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review

#36 Fix discrete HMM model
  Makefile
  examples/discrete_hmm.py
  funsor/distributions.py
  funsor/torch.py
Labels: awaiting review

#38 Remove pattern.py and obsolete code in distributions.py
  funsor/distributions.py
  funsor/pattern.py
Labels: awaiting review, easy
