Repository pyro-ppl/funsor, pull requests merged in 2019-05, with the labels that each got.

#135 Add BernoulliLogits distribution
  funsor/distributions.py
  test/test_distributions.py
Labels: awaiting review, easy

#136 Refactor elbos
  funsor/minipyro.py
Labels: awaiting review, refactor

#137 Add generic Bernoulli wrapper around probs,logits version
  funsor/distributions.py
  test/test_distributions.py
Labels: awaiting review, easy

#140 Simplify minipyro and test
  funsor/minipyro.py
  test/test_minipyro.py
Labels: awaiting review

#126 Add model and guide auxiliary variable elimination to minipyro.elbo
  funsor/minipyro.py
  funsor/sum_product.py
  test/test_minipyro.py
Labels: awaiting review

#141 Update CI to use PyTorch 1.1.0
  .travis.yml
  test/test_torch.py
Labels: awaiting review, easy

#142 Promote Einsum to a funsor for pattern matching
  funsor/__init__.py
  funsor/torch.py
  test/test_torch.py
Labels: awaiting review, refactor

#143 Update badge to point to travis-ci.com
  README.md
Labels: awaiting review, easy

#147 Add an explicit stack-based interpreter
  Makefile
  funsor/interpreter.py
  funsor/terms.py
Labels: awaiting review
