Repository pyro-ppl/funsor, pull requests merged in 2019-07, with the labels that each got.

#161 Implement log-time sequential sum product function
  funsor/domains.py
  funsor/sum_product.py
  test/test_sum_product.py
Labels: awaiting review

#168 Drop python2 support from setup.py and travis.yml
  .travis.yml
  setup.py
Labels: awaiting review, easy

#170 Add FunsorDistribution to wrap funsors for use in Pyro
  docs/source/index.rst
  docs/source/pyro.rst
  funsor/pyro/__init__.py
  funsor/pyro/convert.py
  funsor/pyro/distribution.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch.py
  test/pyro/conftest.py
  test/pyro/test_convert.py
  test/pyro/test_distribution.py
Labels: awaiting review

#172 Drop Python 2 support
  docs/requirements.txt
  examples/discrete_hmm.py
  examples/kalman_filter.py
  examples/minipyro.py
  examples/pcfg.py
  examples/slds.py
  examples/ss_vae_delayed.py
  examples/vae.py
  funsor/__init__.py
  funsor/adjoint.py
  funsor/affine.py
  funsor/contract.py
  funsor/delta.py
  funsor/distributions.py
  funsor/domains.py
  funsor/einsum.py
  funsor/gaussian.py
  funsor/integrate.py
  funsor/interpreter.py
  funsor/joint.py
  funsor/minipyro.py
  funsor/montecarlo.py
  funsor/numpy.py
  funsor/ops.py
  funsor/optimizer.py
  funsor/pattern.py
  funsor/pyro/convert.py
  funsor/pyro/distribution.py
  funsor/registry.py
  funsor/six.py
  funsor/sum_product.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch.py
  funsor/util.py
  setup.cfg
  setup.py
  test/conftest.py
  test/pyro/conftest.py
  test/pyro/test_convert.py
  test/pyro/test_distribution.py
  test/test_adjoint.py
  test/test_affine.py
  test/test_alpha_conversion.py
  test/test_contract.py
  test/test_delta.py
  test/test_distributions.py
  test/test_einsum.py
  test/test_gaussian.py
  test/test_joint.py
  test/test_minipyro.py
  test/test_numpy.py
  test/test_optimizer.py
  test/test_pattern.py
  test/test_samplers.py
  test/test_sum_product.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review, easy, refactor

#174 Refactor pyro converters
  funsor/pyro/convert.py
  funsor/pyro/distribution.py
  test/pyro/test_convert.py
  test/pyro/test_distribution.py
Labels: awaiting review

#160 Add a memoize interpreter/context manager
  funsor/__init__.py
  funsor/memoize.py
  test/test_memoize.py
Labels: awaiting review

#175 Use @singledispatch in dist_to_funsor; add more distributions
  funsor/pyro/convert.py
  funsor/terms.py
  funsor/torch.py
  test/pyro/test_convert.py
Labels: awaiting review

#171 Implement DiscreteHMM as a FunsorDistributions
  docs/source/pyro.rst
  funsor/pyro/__init__.py
  funsor/pyro/convert.py
  funsor/pyro/hmm.py
  funsor/sum_product.py
  test/pyro/test_convert.py
  test/pyro/test_hmm.py
Labels: awaiting review, enhancement

#165 Refactor optimizer to use Contraction and normalize
  funsor/__init__.py
  funsor/adjoint.py
  funsor/contract.py
  funsor/einsum.py
  funsor/integrate.py
  funsor/optimizer.py
  funsor/torch.py
  test/test_contract.py
  test/test_optimizer.py
Labels: awaiting review, refactor

#173 Refactor Affine into Contraction
  funsor/__init__.py
  funsor/affine.py
  funsor/cnf.py
  funsor/distributions.py
  funsor/ops.py
  funsor/terms.py
  test/test_affine.py
  test/test_cnf.py
Labels: awaiting review, refactor

#176 Support Gaussian funsors in sequential_sum_product
  funsor/joint.py
  funsor/sum_product.py
  test/test_sum_product.py
Labels: awaiting review

#178 Implement partial substitution of Gaussian funsors
  funsor/gaussian.py
  test/test_gaussian.py
Labels: awaiting review

#179 Implement funsor.pyro.GaussianMRF
  funsor/pyro/__init__.py
  funsor/pyro/convert.py
  funsor/pyro/hmm.py
  test/pyro/test_convert.py
  test/pyro/test_hmm.py
Labels: awaiting review

#169 Refactor Joint into multivariate Delta and Contraction
  funsor/cnf.py
  funsor/delta.py
  funsor/gaussian.py
  funsor/integrate.py
  funsor/joint.py
  funsor/minipyro.py
  funsor/montecarlo.py
  funsor/pyro/distribution.py
  funsor/sum_product.py
  funsor/testing.py
  test/test_cnf.py
  test/test_distributions.py
  test/test_gaussian.py
  test/test_joint.py
  test/test_samplers.py
Labels: refactor
