Repository pyro-ppl/funsor, pull requests merged in 2019-06, with the labels that each got.

#150 Use classifiers to specify the license
  setup.py
Labels: awaiting review, easy

#148 Alpha renaming of bound variables
  Makefile
  funsor/affine.py
  funsor/contract.py
  funsor/delta.py
  funsor/gaussian.py
  funsor/integrate.py
  funsor/interpreter.py
  funsor/joint.py
  funsor/numpy.py
  funsor/terms.py
  funsor/torch.py
  test/test_adjoint.py
  test/test_alpha_conversion.py
  test/test_terms.py
Labels: awaiting review

#152 Remove most eager_subs methods from terms with no fresh variables
  Makefile
  funsor/affine.py
  funsor/contract.py
  funsor/distributions.py
  funsor/gaussian.py
  funsor/integrate.py
  funsor/interpreter.py
  funsor/optimizer.py
  funsor/terms.py
  funsor/torch.py
  test/test_adjoint.py
  test/test_alpha_conversion.py
Labels: awaiting review

#153 Separate generic and fresh variables in substitute
  funsor/delta.py
  funsor/numpy.py
  funsor/terms.py
  funsor/torch.py
Labels: awaiting review

#154 Remove eager_subs method from Joint
  funsor/gaussian.py
  funsor/joint.py
Labels: awaiting review

#155 Make substitution an interpretation
  Makefile
  funsor/delta.py
  funsor/interpreter.py
  funsor/joint.py
  funsor/numpy.py
  funsor/terms.py
  test/test_numpy.py
Labels: awaiting review, refactor
