Repository pyro-ppl/funsor, pull requests merged in 2019-03, with the labels that each got.

#41 Add simple wrapper around torch.einsum
  funsor/__init__.py
  funsor/torch.py
  test/test_torch.py
Labels: awaiting review

#42 Attempt to fix test seed in pytest
  test/conftest.py
Labels: awaiting review

#43 Refactor and simplify align_tensor()
  funsor/torch.py
Labels: awaiting review, easy

#44 Fix filling in of defaults for distribution classes
  examples/discrete_hmm.py
  funsor/distributions.py
  test/test_distributions.py
Labels: awaiting review

#40 Reinstate opt_einsum-based optimizer
  funsor/ops.py
  funsor/optimizer.py
  funsor/testing.py
  test/test_einsum.py
  test/test_optimizer.py
Labels: awaiting review

#37 Implement general Gaussian funsor
  Makefile
  examples/kalman_filter.py
  funsor/__init__.py
  funsor/distributions.py
  funsor/domains.py
  funsor/gaussian.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch.py
  test/test_distributions.py
  test/test_gaussian.py
  test/test_torch.py
Labels: awaiting review, enhancement

#46 Add plated einsum implementation
  funsor/__init__.py
  funsor/einsum.py
  funsor/ops.py
  funsor/testing.py
  funsor/torch.py
  test/test_einsum.py
  test/test_optimizer.py
  test/test_torch.py
Labels: awaiting review, examples

#47 Fix path evaluation order in optimizer
  funsor/optimizer.py
  test/test_einsum.py
  test/test_optimizer.py
Labels: bug

#49 Add a simple Delta distribution
  funsor/distributions.py
  funsor/testing.py
  test/test_distributions.py
Labels: awaiting review

#55 Implement Op wrapper class to enable pattern matching
  funsor/distributions.py
  funsor/interpreter.py
  funsor/ops.py
  funsor/optimizer.py
Labels: awaiting review, refactor

#56 Update minipyro storyboard to correctly handle plates
  funsor/minipyro.py
Labels: awaiting review

#62 Add type check in Funsor.__call__()
  examples/discrete_hmm.py
  funsor/terms.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review

#63 Match Op type rather than object
  funsor/gaussian.py
  funsor/ops.py
  funsor/optimizer.py
  funsor/terms.py
  funsor/torch.py
Labels: awaiting review, easy

#60 Refactor contract
  funsor/__init__.py
  funsor/contract.py
  funsor/einsum.py
  funsor/testing.py
  test/test_contract.py
Labels: awaiting review, refactor

#67 Add lazy option to HMM examples
  Makefile
  examples/discrete_hmm.py
  examples/kalman_filter.py
Labels: awaiting review, easy, examples

#66 Make reduction methods operate over events
  README.md
  examples/discrete_hmm.py
  examples/kalman_filter.py
  examples/minipyro.py
  funsor/minipyro.py
  funsor/terms.py
  funsor/torch.py
  test/test_gaussian.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review

#64 Add prototype funsor.adjoint module
  funsor/__init__.py
  funsor/adjoint.py
  funsor/einsum.py
  funsor/ops.py
  funsor/optimizer.py
  funsor/testing.py
  test/test_adjoint.py
  test/test_optimizer.py
Labels: awaiting review, discussion

#58 Add numpy backend for funsor
  funsor/numpy.py
  funsor/terms.py
  funsor/testing.py
  test/test_numpy.py
Labels: awaiting review

#73 Implement MultivariateNormal distribution
  funsor/distributions.py
  test/test_distributions.py
Labels: awaiting review, easy

#65 Implement a general Delta funsor
  funsor/__init__.py
  funsor/delta.py
  funsor/distributions.py
  funsor/ops.py
  funsor/terms.py
  test/test_delta.py
  test/test_distributions.py
Labels: awaiting review

#74 Separate out ops implementations based on backend
  funsor/ops.py
  funsor/registry.py
  funsor/torch.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review, discussion

#69 Implement a Joint normal form funsor
  funsor/__init__.py
  funsor/distributions.py
  funsor/gaussian.py
  funsor/joint.py
  funsor/ops.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch.py
  test/test_delta.py
  test/test_distributions.py
  test/test_gaussian.py
  test/test_joint.py
Labels: awaiting review

#76 Implement sequential interpretation
  funsor/interpreter.py
  funsor/optimizer.py
  funsor/terms.py
  test/test_terms.py
Labels: awaiting review, refactor

#75 Implement monte carlo .sample() methods
  funsor/delta.py
  funsor/domains.py
  funsor/gaussian.py
  funsor/joint.py
  funsor/minipyro.py
  funsor/ops.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch.py
  test/test_gaussian.py
  test/test_samplers.py
Labels: awaiting review

#81 Rename funsor.contract module to funsor.sum_product
  funsor/__init__.py
  funsor/einsum.py
  funsor/minipyro.py
  funsor/sum_product.py
  test/test_sum_product.py
Labels: awaiting review, easy

#82 Support torch functions that return nested tuples of tensors
  examples/ss_vae_delayed.py
  funsor/__init__.py
  funsor/torch.py
  test/test_distributions.py
  test/test_torch.py
Labels: awaiting review, enhancement

#84 Add a to_data() helper
  funsor/__init__.py
  funsor/numpy.py
  funsor/terms.py
  funsor/torch.py
  test/test_numpy.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review, enhancement

#77 Implement Contract term
  funsor/__init__.py
  funsor/contract.py
  funsor/einsum.py
  funsor/optimizer.py
  test/test_contract.py
Labels: awaiting review

#91 Refactor contract dependencies
  funsor/contract.py
  funsor/torch.py
Labels: awaiting review, refactor

#87 Sketched a simple PCFG example
  Makefile
  examples/pcfg.py
  funsor/terms.py
Labels: awaiting review, examples

#92 Add isort command to Makefile
  Makefile
  examples/ss_vae_delayed.py
  funsor/__init__.py
  funsor/adjoint.py
  funsor/einsum.py
  funsor/ops.py
  funsor/sum_product.py
  setup.cfg
  test/test_adjoint.py
  test/test_contract.py
  test/test_einsum.py
  test/test_numpy.py
  test/test_optimizer.py
  test/test_sum_product.py
  test/test_terms.py
Labels: awaiting review, easy

#88 Implement advanced indexing in Funsor.__getitem__()
  funsor/domains.py
  funsor/numpy.py
  funsor/ops.py
  funsor/terms.py
  funsor/torch.py
  test/test_torch.py
Labels: awaiting review

#93 Add interpretation logging controlled by FUNSOR_DEBUG=1
  funsor/interpreter.py
  funsor/terms.py
Labels: awaiting review, easy

#94 Fix lazy reduction for Joint.reduce()
  funsor/joint.py
  test/test_joint.py
Labels: awaiting review, bug

#54 Implement Monte Carlo interpretation of Integrate
  funsor/__init__.py
  funsor/delta.py
  funsor/gaussian.py
  funsor/integrate.py
  funsor/interpreter.py
  funsor/joint.py
  funsor/montecarlo.py
  funsor/ops.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch.py
  test/test_gaussian.py
  test/test_samplers.py
  test/test_torch.py
Labels: awaiting review

#99 Resurrect lazy Subs funsor (again)
  funsor/contract.py
  funsor/delta.py
  funsor/distributions.py
  funsor/gaussian.py
  funsor/joint.py
  funsor/numpy.py
  funsor/optimizer.py
  funsor/terms.py
  funsor/torch.py
Labels: awaiting review

#101 Log function and filename when FUNSOR_DEBUG=1
  Makefile
  funsor/contract.py
  funsor/integrate.py
  funsor/interpreter.py
  funsor/joint.py
  funsor/registry.py
  funsor/terms.py
Labels: awaiting review

#102 Remove modified version of minipyro
  funsor/__init__.py
  funsor/handlers.py
  funsor/minipyro.py
Labels: awaiting review

#78 Support for pattern matching with the unification library
  funsor/__init__.py
  funsor/pattern.py
  setup.py
  test/test_pattern.py
Labels: awaiting review

#103 Implement basic transformed distributions
  funsor/delta.py
  funsor/distributions.py
  funsor/gaussian.py
  funsor/joint.py
  funsor/ops.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch.py
  test/test_delta.py
  test/test_distributions.py
  test/test_gaussian.py
  test/test_samplers.py
Labels: awaiting review

#104 Implement negation and subtraction ops for R-N derivatives
  funsor/delta.py
  funsor/gaussian.py
  funsor/joint.py
  funsor/ops.py
  test/test_gaussian.py
  test/test_joint.py
Labels: awaiting review

#105 Add Contract to optimizer
  funsor/adjoint.py
  funsor/contract.py
  funsor/einsum.py
  funsor/integrate.py
  funsor/ops.py
  funsor/optimizer.py
  funsor/torch.py
  test/test_contract.py
  test/test_optimizer.py
Labels: awaiting review

#107 Make distributions lazy when used Pyro-style
  funsor/distributions.py
  test/test_distributions.py
Labels: awaiting review

#108 Implement plate reductions for Gaussian, Joint
  funsor/gaussian.py
  funsor/joint.py
  test/test_gaussian.py
  test/test_joint.py
Labels: awaiting review

#100 Add a working minipyro with tests
  .travis.yml
  funsor/__init__.py
  funsor/joint.py
  funsor/minipyro.py
  funsor/terms.py
  test/conftest.py
  test/test_minipyro.py
Labels: awaiting review

#111 Support event_dim kwarg in pyro.param
  funsor/minipyro.py
  test/test_minipyro.py
Labels: awaiting review

#112 Change to_funsor's second arg from dtype to Domain
  funsor/distributions.py
  funsor/numpy.py
  funsor/terms.py
  funsor/torch.py
  test/test_distributions.py
  test/test_numpy.py
  test/test_torch.py
Labels: awaiting review, refactor

#113 Simplify .unscaled_sample() interface
  funsor/gaussian.py
  funsor/joint.py
  funsor/terms.py
  funsor/torch.py
Labels: awaiting review, easy, refactor
