Repository pyro-ppl/funsor, pull requests merged in 2019-08, with the labels that each got.

#181 Add arg validation logic to funsor.pyro.FunsorDistribution
  funsor/pyro/distribution.py
  funsor/pyro/hmm.py
  test/pyro/test_distribution.py
Labels: awaiting review, easy

#183 Support multiple latent variables in sequential_sum_product()
  funsor/sum_product.py
  test/test_sum_product.py
Labels: awaiting review

#186 Refactor Gaussian to use information form
  funsor/distributions.py
  funsor/gaussian.py
  funsor/joint.py
  funsor/pyro/convert.py
  funsor/sum_product.py
  funsor/testing.py
  test/pyro/test_convert.py
  test/pyro/test_hmm.py
  test/test_gaussian.py
  test/test_joint.py
Labels: awaiting review, refactor

#185 Implement funsor.pyro.GaussianHMM
  funsor/pyro/__init__.py
  funsor/pyro/convert.py
  funsor/pyro/hmm.py
  funsor/testing.py
  test/pyro/test_convert.py
  test/pyro/test_hmm.py
Labels: awaiting review

#188 Fix normalization bug in moment_matching interpretation
  examples/slds.py
  funsor/gaussian.py
  funsor/joint.py
  test/test_joint.py
Labels: awaiting review, bug

#189 Fix sequential_sum_product, add naive_sequential_sum_product
  funsor/pyro/hmm.py
  funsor/sum_product.py
  test/pyro/test_hmm.py
  test/test_sum_product.py
Labels: awaiting review, bug

#187 Implement funsor.pyro.SwitchingLinearHMM
  funsor/pyro/__init__.py
  funsor/pyro/hmm.py
  test/pyro/test_hmm.py
Labels: awaiting review

#192 Update to PyTorch 1.2
  .travis.yml
  funsor/testing.py
  funsor/torch.py
  test/test_torch.py
Labels: awaiting review, easy

#195 add failing gaussian hmm test
  funsor/testing.py
  test/pyro/test_hmm.py
Labels: awaiting review

#196 Numerically stabilize moment_matching approximation
  funsor/joint.py
  funsor/torch.py
  test/test_joint.py
Labels: awaiting review

#197 Update adjoint to support different forward and backward interpretations
  funsor/adjoint.py
  funsor/terms.py
  funsor/torch.py
  test/test_adjoint.py
Labels: awaiting review, enhancement, refactor

#194 add slds log_prob test
  test/pyro/test_hmm.py
Labels: awaiting review, easy

#198 Add additional einsum backend support
  Makefile
  funsor/adjoint.py
  funsor/einsum.py
  funsor/testing.py
  setup.py
  test/test_adjoint.py
  test/test_einsum.py
  test/test_optimizer.py
Labels: awaiting review

#200 fix broken docs
  docs/source/conf.py
Labels: awaiting review

#202 Add more docs, especially funsor.pyro.convert
  docs/source/funsors.rst
  docs/source/index.rst
  docs/source/interpretations.rst
  docs/source/pyro.rst
  docs/source/sum_product.rst
  docs/source/testing.rst
  funsor/pyro/convert.py
Labels: awaiting review

#205 Promote Slice to a funsor
  funsor/__init__.py
  funsor/gaussian.py
  funsor/sum_product.py
  funsor/terms.py
  funsor/torch.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review
