Repository pyro-ppl/funsor, pull requests merged in 2020-12, with the labels that each got.

#403 Partial unrolling of plated factor graphs to standard factor graphs
  funsor/sum_product.py
  test/test_sum_product.py
Labels: awaiting response, testing

#406 Allow empty tensor conversion
  funsor/tensor.py
  test/test_tensor.py
Labels: awaiting review

#404 Update partial_unroll to support markov dims
  funsor/sum_product.py
  test/test_sum_product.py
Labels: awaiting review, refactor, testing

#407 Update modified_partial_sum_product to sum over init factors
  funsor/sum_product.py
  test/test_sum_product.py
Labels: awaiting review

#402 Update distribution shape inference to handle independent dims
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/torch/distributions.py
  test/test_distribution.py
Labels: awaiting review

#409 Support partial windows in sarkka_bilmes_product
  funsor/sum_product.py
  test/test_sum_product.py
Labels: awaiting review

#415 Change P to _PREV_ in sarkka_bilmes_generic
  funsor/sum_product.py
  test/test_sum_product.py
Labels: awaiting review
