Repository pyro-ppl/funsor, pull requests merged in 2020-08, with the labels that each got.

#346 Add a generic enumerate_support method
  funsor/distribution.py
  test/test_distribution.py
Labels: awaiting review

#345 Add Dirichlet Multinomial conjugacy
  funsor/torch/distributions.py
  test/test_distribution.py
Labels: awaiting review

#349 Make torch backend log return the correct dtype of a boolean tensor
  funsor/torch/ops.py
  test/test_tensor.py
Labels: awaiting review, bug, easy

#353 Fix sphinx warning about lazy_property
  funsor/util.py
Labels: awaiting review, easy

#350 Support copy, deepcopy, pickle, detach
  funsor/domains.py
  funsor/ops.py
  funsor/terms.py
  scripts/update_headers.py
  setup.cfg
  test/test_domains.py
  test/test_tensor.py
  test/test_terms.py
Labels: awaiting review

#352 Refactor domains to be types
  funsor/__init__.py
  funsor/distribution.py
  funsor/domains.py
  funsor/interpreter.py
  funsor/pyro/convert.py
  funsor/tensor.py
  funsor/terms.py
  test/test_cnf.py
  test/test_domains.py
  test/test_tensor.py
  test/test_terms.py
Labels: awaiting review, refactor

#356 Unify Reals,Bint into Array
  funsor/__init__.py
  funsor/distribution.py
  funsor/domains.py
  funsor/interpreter.py
  funsor/pyro/convert.py
  funsor/tensor.py
  test/test_domains.py
  test/test_tensor.py
  test/test_terms.py
Labels: awaiting review, refactor

#354 Add minimal type annotation support to funsors
  funsor/__init__.py
  funsor/tensor.py
  funsor/terms.py
  setup.cfg
  setup.py
  test/test_distribution.py
  test/test_tensor.py
  test/test_terms.py
Labels: awaiting review

#357 Replace bint -> Bint, reals -> Reals throughout codebase
  examples/discrete_hmm.py
  examples/eeg_slds.py
  examples/kalman_filter.py
  examples/mixed_hmm/model.py
  examples/pcfg.py
  examples/sensor.py
  examples/slds.py
  examples/vae.py
  funsor/adjoint.py
  funsor/affine.py
  funsor/delta.py
  funsor/distribution.py
  funsor/domains.py
  funsor/gaussian.py
  funsor/jax/distributions.py
  funsor/joint.py
  funsor/minipyro.py
  funsor/pyro/convert.py
  funsor/pyro/distribution.py
  funsor/pyro/hmm.py
  funsor/sum_product.py
  funsor/tensor.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch/distributions.py
  test/examples/test_bart.py
  test/examples/test_sensor_fusion.py
  test/pyro/test_convert.py
  test/test_adjoint.py
  test/test_affine.py
  test/test_alpha_conversion.py
  test/test_cnf.py
  test/test_delta.py
  test/test_distribution.py
  test/test_domains.py
  test/test_einsum.py
  test/test_gaussian.py
  test/test_integrate.py
  test/test_joint.py
  test/test_optimizer.py
  test/test_samplers.py
  test/test_sum_product.py
  test/test_tensor.py
  test/test_terms.py
Labels: awaiting review, refactor
