Repository pyro-ppl/funsor, pull requests merged in 2020-11, with the labels that each got.

#391 Tweak automated registration for distribution-to-funsor conversion
  examples/eeg_slds.py
  examples/sensor.py
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/pyro/convert.py
  funsor/torch/distributions.py
Labels: enhancement, refactor

#389 Automate distribution testing
  Makefile
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/jax/ops.py
  funsor/ops/array.py
  funsor/testing.py
  funsor/torch/distributions.py
  funsor/torch/ops.py
  test/test_distribution.py
  test/test_distribution_generic.py
Labels: awaiting review, refactor, testing

#394 Add support for most remaining atomic distributions
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/testing.py
  funsor/torch/distributions.py
  test/test_distribution_generic.py
Labels: awaiting review

#396 Support converting funsor.terms.Independent to and from data
  funsor/distribution.py
  funsor/terms.py
  test/test_distribution_generic.py
Labels: awaiting review

#392 Support conjugacy for beta plate binomial
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/memoize.py
  funsor/terms.py
  funsor/torch/distributions.py
  test/test_distribution.py
Labels: awaiting review

#365 Support conversion of Transforms and TransformedDistributions to and from Funsors
  funsor/cnf.py
  funsor/distribution.py
  funsor/torch/distributions.py
  test/test_distribution_generic.py
  test/test_samplers.py
Labels: awaiting review

#398 Generalize partial sum product to Markov models
  funsor/sum_product.py
  test/test_sum_product.py
Labels: WIP, enhancement

#401 Disable validation in VAE example
  examples/vae.py
Labels: awaiting review, bug, easy, testing

#400 Update modified_partial_sum_product to use MarkovProduct and add test
  funsor/sum_product.py
  test/test_sum_product.py
Labels: awaiting review
