Repository pyro-ppl/funsor, pull requests merged in 2020-01, with the labels that each got.

#298 Implement Cat.eager_subs for Slices
  .travis.yml
  funsor/terms.py
  funsor/torch.py
  setup.py
  test/test_terms.py
Labels: awaiting review

#299 Add a sequential_sum_product implementation that interpolates between serial and parallel scans
  funsor/sum_product.py
  test/test_sum_product.py
Labels: awaiting review

#297 Add some ops required for Gaussian
  funsor/gaussian.py
  funsor/numpy.py
  funsor/ops.py
  funsor/torch.py
  test/test_gaussian.py
  test/test_numpy.py
Labels: awaiting review

#300 Simplify numpy op wrappers
  funsor/numpy.py
  setup.cfg
Labels: awaiting review, easy

#296 refactor Gaussian to use Tensor api instead of torch.Tensor
  funsor/distributions.py
  funsor/gaussian.py
  funsor/integrate.py
  funsor/joint.py
  funsor/numpy.py
  funsor/ops.py
  funsor/pyro/convert.py
  funsor/torch.py
  setup.py
  test/test_gaussian.py
Labels: awaiting review

#306 Add ops.sample
  .travis.yml
  funsor/ops.py
  funsor/terms.py
  funsor/torch.py
  test/test_terms.py
  test/test_torch.py
Labels: awaiting review

#303 make Tensor backend agnostic
  Makefile
  examples/mixed_hmm/model.py
  examples/pcfg.py
  examples/sensor.py
  examples/vae.py
  funsor/__init__.py
  funsor/adjoint.py
  funsor/affine.py
  funsor/cnf.py
  funsor/distributions.py
  funsor/gaussian.py
  funsor/integrate.py
  funsor/joint.py
  funsor/minipyro.py
  funsor/numpy.py
  funsor/ops.py
  funsor/pyro/convert.py
  funsor/tensor.py
  funsor/testing.py
  funsor/torch.py
  test/examples/test_bart.py
  test/examples/test_sensor_fusion.py
  test/pyro/test_convert.py
  test/test_affine.py
  test/test_cnf.py
  test/test_delta.py
  test/test_distributions.py
  test/test_einsum.py
  test/test_gaussian.py
  test/test_joint.py
  test/test_numpy.py
  test/test_optimizer.py
  test/test_samplers.py
  test/test_sum_product.py
  test/test_tensor.py
  test/test_terms.py
Labels: awaiting response

#310 Add Makefile target for update_license.py
  Makefile
  scripts/update_headers.py
Labels: awaiting review, easy

#312 Support numpy docs for getargspec
  funsor/interpreter.py
  funsor/util.py
  test/test_tensor.py
Labels: awaiting review, easy
