Repository pyro-ppl/funsor, pull requests merged in 2020-10, with the labels that each got.

#377 Add DirichletMultinomial for jax backend
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/jax/ops.py
  funsor/torch/distributions.py
  test/test_distribution.py
Labels: awaiting review

#378 Add beta bernoulli conjugacy
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/torch/distributions.py
  test/test_distribution.py
Labels: awaiting review

#379 Add gamma poisson conjugacy
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/torch/distributions.py
  test/test_distribution.py
Labels: awaiting review

#380 Require torch>=1.6; drop support for Python 3.5
  .travis.yml
  setup.py
Labels: awaiting review, easy

#382 Materialize diagonal name substitutions in Tensor.eager_subs
  funsor/tensor.py
  test/test_tensor.py
Labels: awaiting review, bug, easy

#383 bump setup.py version to 0.3
  setup.py
Labels: awaiting review, easy

#384 Add DirichletCategorical conjugacy
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/torch/distributions.py
  test/test_distribution.py
Labels: awaiting review

#385 Add Gamma Gamma conjugacy
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/jax/ops.py
  funsor/ops/builtin.py
  funsor/terms.py
  funsor/torch/distributions.py
  funsor/torch/ops.py
  test/test_distribution.py
Labels: awaiting review

#387 Add TanhOp and AtanhOp
  funsor/jax/ops.py
  funsor/ops/array.py
  funsor/ops/builtin.py
  funsor/terms.py
  funsor/torch/ops.py
  test/test_tensor.py
  test/test_terms.py
Labels: awaiting review

#388 Add generic stat methods to Distribution
  funsor/distribution.py
  test/test_distribution.py
Labels: awaiting review
