Repository pyro-ppl/funsor, pull requests merged in 2020-07, with the labels that each got.

#329 Make Funsor compatible with Python 3.5
  .travis.yml
  examples/eeg_slds.py
  examples/sensor.py
  funsor/affine.py
  funsor/cnf.py
  funsor/distribution.py
  funsor/interpreter.py
  funsor/jax/__init__.py
  funsor/ops.py
  funsor/pyro/convert.py
  funsor/pyro/distribution.py
  funsor/pyro/hmm.py
  funsor/registry.py
  funsor/sum_product.py
  funsor/tensor.py
  funsor/terms.py
  funsor/torch/__init__.py
  funsor/util.py
  setup.py
  test/pyro/test_hmm.py
  test/test_adjoint.py
  test/test_cnf.py
  test/test_gaussian.py
  test/test_import.py
  test/test_joint.py
  test/test_sum_product.py
  test/test_terms.py
Labels: awaiting review, bug, testing

#337 Import pytest lazily and remove install dependency
  funsor/testing.py
  setup.py
Labels: awaiting review, easy, testing

#340 Pin pytest to 4.3.1
  setup.py
Labels: awaiting review, testing

#339 make funsor[jax] work for numpyro 0.2.4
  .travis.yml
  funsor/domains.py
  funsor/jax/distributions.py
  setup.py
  test/test_distribution.py
Labels: awaiting review

#341 Bump to version 0.2.0
  .travis.yml
  setup.py
  test/test_distribution.py
Labels: awaiting review

#342 Fix apache license
  setup.py
Labels: awaiting review

#344 Fix docs
  docs/requirements.txt
  docs/source/distributions.rst
  docs/source/funsors.rst
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/tensor.py
  funsor/torch/distributions.py
Labels: awaiting review
