Repository pyro-ppl/funsor, pull requests merged in 2020-05, with the labels that each got.

#328 Fix a userwarning about integer divison in PyTorch 1.5
  Makefile
  examples/eeg_slds.py
  funsor/tensor.py
  funsor/util.py
  setup.cfg
Labels: awaiting review, bug, easy

#330 Pin pyro-api version
  setup.py
Labels: awaiting review, easy

#327 Make funsor.distributions backend agnostic
  .travis.yml
  Makefile
  docs/source/distributions.rst
  docs/source/funsors.rst
  examples/discrete_hmm.py
  examples/eeg_slds.py
  examples/kalman_filter.py
  examples/mixed_hmm/model.py
  examples/sensor.py
  examples/slds.py
  examples/vae.py
  funsor/__init__.py
  funsor/cnf.py
  funsor/delta.py
  funsor/distribution.py
  funsor/gaussian.py
  funsor/jax/__init__.py
  funsor/jax/distributions.py
  funsor/jax/ops.py
  funsor/ops.py
  funsor/pyro/convert.py
  funsor/tensor.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch/__init__.py
  funsor/torch/distributions.py
  funsor/torch/ops.py
  setup.cfg
  setup.py
  test/__init__.py
  test/examples/test_bart.py
  test/examples/test_sensor_fusion.py
  test/test_adjoint.py
  test/test_delta.py
  test/test_distribution.py
  test/test_einsum.py
  test/test_gaussian.py
  test/test_import.py
  test/test_joint.py
  test/test_memoize.py
  test/test_minipyro.py
  test/test_optimizer.py
  test/test_samplers.py
  test/test_tensor.py
Labels: awaiting review
