Repository pyro-ppl/funsor, pull requests merged in 2021-01, with the labels that each got.

#397 Allow .reduce(op, vars_not_in_inputs)
  funsor/adjoint.py
  funsor/cnf.py
  funsor/delta.py
  funsor/distribution.py
  funsor/einsum/__init__.py
  funsor/gaussian.py
  funsor/integrate.py
  funsor/joint.py
  funsor/montecarlo.py
  funsor/optimizer.py
  funsor/sum_product.py
  funsor/tensor.py
  funsor/terms.py
  test/examples/test_bart.py
  test/test_cnf.py
  test/test_terms.py
Labels: awaiting review

#418 Add method for converting Pyro ExpandedDistribution to funsor
  funsor/distribution.py
  funsor/torch/distributions.py
  test/test_distribution_generic.py
Labels: awaiting review

#419 support ExpandedDistribution for jax backend
  funsor/distribution.py
  funsor/jax/distributions.py
  test/test_distribution_generic.py
Labels: awaiting review

#420 Avoid creating distributions when inferring value domain
  funsor/distribution.py
  funsor/jax/distributions.py
  funsor/memoize.py
  funsor/tensor.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch/distributions.py
Labels: awaiting review, refactor

#421 Unify op-caching metaclasses
  funsor/ops/array.py
  funsor/ops/builtin.py
  funsor/ops/op.py
Labels: awaiting review, refactor

#422 Break up type inference rules in find_domain into op-level patterns
  funsor/adjoint.py
  funsor/cnf.py
  funsor/domains.py
  funsor/integrate.py
  funsor/jax/distributions.py
  funsor/joint.py
  funsor/ops/array.py
  funsor/ops/builtin.py
  funsor/ops/op.py
  funsor/torch/distributions.py
  test/test_terms.py
Labels: awaiting review, refactor

#432 Support IndependentConstraint in Distribution._infer_param_domain
  funsor/distribution.py
Labels: awaiting review, bug

#431 Add automatic registration of all unary and associative ops
  funsor/jax/ops.py
  funsor/ops/array.py
  funsor/ops/builtin.py
  funsor/ops/op.py
  funsor/terms.py
  funsor/torch/ops.py
Labels: awaiting review, refactor

#430 Add Tuple funsor
  funsor/domains.py
  funsor/tensor.py
  funsor/terms.py
  test/test_tensor.py
  test/test_terms.py
Labels: awaiting review, enhancement, refactor

#435 Add profiling counters via FUNSOR_PROFILE=1
  Makefile
  funsor/interpreter.py
  funsor/optimizer.py
  funsor/terms.py
  test/test_distribution_generic.py
Labels: awaiting review

#439 Bump to version 0.4.0
  setup.py
Labels: awaiting review

#440 Prettify generic distribution tests
  test/test_distribution_generic.py
Labels: awaiting review, easy

#442 Add a @make_funsor factory for Funsor subclasses
  docs/source/factory.rst
  docs/source/index.rst
  funsor/factory.py
  funsor/registry.py
  test/test_factory.py
Labels: awaiting review, enhancement

#443 Directly convert IndependentDistribution to base distribution
  funsor/distribution.py
  test/test_distribution_generic.py
Labels: awaiting review

#427 Add factory for dynamic TransformOp
  funsor/distribution.py
  funsor/domains.py
  funsor/jax/distributions.py
  funsor/ops/builtin.py
  funsor/ops/op.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch/distributions.py
  setup.cfg
  test/test_distribution.py
  test/test_distribution_generic.py
  test/test_ops.py
Labels: awaiting review
