Repository pyro-ppl/funsor, pull requests merged in 2021-11, with the labels that each got.

#579 Support ops with namedtuple output in ProvenanceTensor
  funsor/torch/provenance.py
  test/test_gaussian.py
  test/torch/test_provenance.py
Labels: bug, awaiting review, easy

#580 Typo in Approximate
  funsor/__init__.py
  funsor/terms.py
Labels: awaiting review, easy

#553 Add Precondition interpretation for Gaussian TVE
  docs/source/interpretations.rst
  funsor/__init__.py
  funsor/adjoint.py
  funsor/cnf.py
  funsor/domains.py
  funsor/gaussian.py
  funsor/jax/ops.py
  funsor/montecarlo.py
  funsor/ops/array.py
  funsor/precondition.py
  funsor/recipes.py
  funsor/tensor.py
  funsor/torch/ops.py
  test/test_gaussian.py
  test/test_recipes.py
  test/test_terms.py
Labels: awaiting review
