Repository pyro-ppl/funsor, pull requests merged in 2021-09, with the labels that each got.

#549 Add recipes.forward_filter_backward_rsample()
  docs/source/index.rst
  docs/source/recipes.rst
  funsor/__init__.py
  funsor/adjoint.py
  funsor/approximations.py
  funsor/cnf.py
  funsor/delta.py
  funsor/distribution.py
  funsor/gaussian.py
  funsor/montecarlo.py
  funsor/recipes.py
  funsor/tensor.py
  funsor/terms.py
  funsor/testing.py
  test/test_approximations.py
  test/test_distribution.py
  test/test_gaussian.py
  test/test_integrate.py
  test/test_joint.py
  test/test_recipes.py
  test/test_samplers.py
  test/test_tensor.py
Labels: enhancement, awaiting response

#548 Constant Funsor
  funsor/__init__.py
  funsor/constant.py
  funsor/torch/__init__.py
  test/test_constant.py
Labels: enhancement, awaiting review

#551 Dispatch to `Integrate(Delta, ...)` in `normalize_integrate_contraction`
  funsor/distribution.py
  funsor/integrate.py
  test/test_distribution.py
Labels: awaiting review

#554 Rework `Delta.eager_subs` to fix issues related to `_alpha_unmangle`
  funsor/constant.py
  funsor/delta.py
Labels: awaiting review

#555 Add ops.getslice for complex indexing by int,slice,None,Ellipsis
  funsor/affine.py
  funsor/domains.py
  funsor/ops/builtin.py
  funsor/tensor.py
  funsor/terms.py
  funsor/testing.py
  test/test_ops.py
  test/test_tensor.py
  test/test_terms.py
Labels: awaiting review
