Repository pyro-ppl/funsor, pull requests merged in 2021-02, with the labels that each got.

#447 Improve __str__; add ops //, %, <<, >>
  funsor/cnf.py
  funsor/domains.py
  funsor/ops/builtin.py
  funsor/tensor.py
  funsor/terms.py
  test/test_factory.py
  test/test_tensor.py
Labels: awaiting review

#452 Move instrumentation into funsor.instrument module
  funsor/adjoint.py
  funsor/delta.py
  funsor/factory.py
  funsor/instrument.py
  funsor/interpreter.py
  funsor/terms.py
  setup.cfg
Labels: awaiting review, refactor

#450 Reinstate black-compatible isort
  Makefile
  examples/discrete_hmm.py
  examples/eeg_slds.py
  examples/kalman_filter.py
  examples/mixed_hmm/experiment.py
  examples/mixed_hmm/model.py
  examples/sensor.py
  examples/slds.py
  examples/vae.py
  funsor/__init__.py
  funsor/affine.py
  funsor/distribution.py
  funsor/einsum/numpy_map.py
  funsor/integrate.py
  funsor/jax/__init__.py
  funsor/jax/distributions.py
  funsor/jax/ops.py
  funsor/ops/__init__.py
  funsor/ops/builtin.py
  funsor/pyro/distribution.py
  funsor/tensor.py
  funsor/testing.py
  funsor/torch/__init__.py
  funsor/util.py
  scripts/update_headers.py
  setup.cfg
  setup.py
  test/examples/test_bart.py
  test/examples/test_sensor_fusion.py
  test/test_affine.py
  test/test_cnf.py
  test/test_domains.py
  test/test_joint.py
  test/test_memoize.py
  test/test_ops.py
  test/test_optimizer.py
  test/test_sum_product.py
  test/test_tensor.py
Labels: awaiting review

#454 Remove nondeterminism in test_distribution_generic
  test/test_distribution_generic.py
Labels: awaiting review, bug, easy, testing

#455 Add license check to make targets lint and format
  Makefile
  scripts/update_headers.py
Labels: awaiting review, easy

#458 Slightly refactor logic in joint in prep for Approximate
  funsor/joint.py
Labels: awaiting review, easy

#460 Switch to testing with Pyro master branch
  .travis.yml
Labels: awaiting review, easy, testing

#461 Add ops and refactor syntax
  funsor/adjoint.py
  funsor/ops/builtin.py
  funsor/ops/op.py
  funsor/syntax.py
  funsor/terms.py
Labels: awaiting review, easy

#456 Add helper to rewrite infix ops as local variables
  funsor/syntax.py
  test/test_syntax.py
Labels: awaiting review, discussion

#429 Add Interpretation class and refactor some existing interpretations
  docs/source/interpretations.rst
  examples/discrete_hmm.py
  examples/kalman_filter.py
  examples/mixed_hmm/experiment.py
  funsor/__init__.py
  funsor/adjoint.py
  funsor/cnf.py
  funsor/delta.py
  funsor/distribution.py
  funsor/einsum/__init__.py
  funsor/gaussian.py
  funsor/integrate.py
  funsor/interpretations.py
  funsor/interpreter.py
  funsor/jax/distributions.py
  funsor/joint.py
  funsor/memoize.py
  funsor/minipyro.py
  funsor/montecarlo.py
  funsor/optimizer.py
  funsor/pyro/convert.py
  funsor/pyro/hmm.py
  funsor/tensor.py
  funsor/terms.py
  funsor/torch/distributions.py
  test/examples/test_bart.py
  test/test_adjoint.py
  test/test_alpha_conversion.py
  test/test_cnf.py
  test/test_distribution.py
  test/test_distribution_generic.py
  test/test_einsum.py
  test/test_integrate.py
  test/test_joint.py
  test/test_memoize.py
  test/test_optimizer.py
  test/test_samplers.py
  test/test_sum_product.py
  test/test_tensor.py
  test/test_terms.py
Labels: awaiting review, refactor

#462 Add a Value hint to funsor.factory
  funsor/factory.py
  test/test_factory.py
Labels: awaiting review, enhancement

#465 Switch from travis to github actions (second try)
  .github/workflows/ci.yml
  .travis.yml
  README.md
Labels: awaiting review

#466 Update readthedocs page
  .gitignore
  docs/source/_static/img/pyro_logo_wide.png
  docs/source/_templates/breadcrumbs.html
  docs/source/conf.py
  docs/source/index.rst
  examples/README.rst
  examples/discrete_hmm.py
  examples/eeg_slds.py
  examples/kalman_filter.py
  examples/minipyro.py
  examples/mixed_hmm/model.py
  examples/pcfg.py
  examples/sensor.py
  examples/slds.py
  examples/vae.py
  funsor/__init__.py
  scripts/update_headers.py
  setup.py
  tutorials/README.md
Labels: awaiting review

#451 Add a funsor.typing module for runtime dispatch and type-checking
  .github/workflows/ci.yml
  docs/requirements.txt
  docs/source/index.rst
  docs/source/typing.rst
  funsor/cnf.py
  funsor/joint.py
  funsor/optimizer.py
  funsor/registry.py
  funsor/tensor.py
  funsor/terms.py
  funsor/typing.py
  setup.py
  test/test_cnf.py
  test/test_terms.py
  test/test_typing.py
Labels: awaiting review, enhancement, refactor

#467 Add a check to avoid e.g. Variable("x", Reals)
  funsor/domains.py
  funsor/terms.py
Labels: awaiting review, easy

#468 Reduce stack depth of PrioritizedInterpretation; add docs
  docs/source/conf.py
  docs/source/interpretations.rst
  docs/source/ops.rst
  funsor/__init__.py
  funsor/affine.py
  funsor/interpretations.py
  funsor/memoize.py
  funsor/typing.py
  test/test_memoize.py
Labels: awaiting review

#469 Fix Multinomial usage for Pyro dev branch
  test/test_distribution.py
Labels: awaiting review, easy

#463 Add an Elbo interpretation implementing Jensen's inequality
  docs/source/interpretations.rst
  funsor/__init__.py
  funsor/elbo.py
  test/test_elbo.py
Labels: awaiting review

#423 Add Finitary funsor for representing lazy op application
  funsor/affine.py
  funsor/tensor.py
  funsor/terms.py
  test/test_affine.py
  test/test_gaussian.py
  test/test_tensor.py
Labels: awaiting review, refactor

#470 Implement Scatter funsor
  docs/source/conf.py
  funsor/jax/ops.py
  funsor/ops/array.py
  funsor/ops/op.py
  funsor/tensor.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch/ops.py
  setup.cfg
  test/conftest.py
  test/test_tensor.py
Labels: awaiting review
