Repository pyro-ppl/funsor, pull requests merged in 2021-10, with the labels that each got.

#557 Add a compiler and tracer, each creating OpPrograms
  docs/source/compiler.rst
  docs/source/index.rst
  funsor/__init__.py
  funsor/compiler.py
  funsor/ops/__init__.py
  funsor/ops/op.py
  funsor/ops/program.py
  funsor/ops/tracer.py
  funsor/testing.py
  funsor/util.py
  test/test_compiler.py
  test/test_tracer.py
Labels: awaiting review

#562 `find_domain` for `astype`
  funsor/delta.py
  funsor/domains.py
  funsor/util.py
  test/test_cnf.py
Labels: awaiting response

#564 Optimize ops.triangular_solve() for 1x1 matrices
  funsor/torch/ops.py
  test/torch/test_ops.py
Labels: awaiting review, easy

#565 Add `Constant` to `eager_contraction_binary_to_integrate` pattern
  funsor/integrate.py
Labels: awaiting review
