Repository pyro-ppl/funsor, pull requests merged in 2021-03, with the labels that each got.

#473 Temporarily disable VAE example smoke test
  Makefile
Labels: awaiting review, easy

#445 Sketch a transpose() function plus simple algebraic tests
  funsor/adjoint.py
  funsor/cnf.py
  funsor/interpretations.py
  funsor/interpreter.py
  funsor/jax/__init__.py
  funsor/jax/ops.py
  funsor/ops/array.py
  funsor/ops/builtin.py
  funsor/ops/op.py
  funsor/tensor.py
  funsor/terms.py
  funsor/torch/__init__.py
  funsor/torch/ops.py
  test/test_adjoint.py
  test/test_tensor.py
  test/test_transpose.py
Labels: awaiting review

#457 Add an Approximate funsor for use in adjoint algorithms
  docs/source/interpretations.rst
  funsor/__init__.py
  funsor/approximations.py
  funsor/integrate.py
  funsor/interpretations.py
  funsor/jax/ops.py
  funsor/montecarlo.py
  funsor/ops/array.py
  funsor/terms.py
  funsor/torch/ops.py
  test/test_approximations.py
Labels: awaiting review

#472 Add a Has annotation to funsor.factory
  funsor/factory.py
  test/test_factory.py
Labels: awaiting review

#475 Add requirements to make rtd builds pass
  docs/requirements.txt
Labels: awaiting review, easy

#428 Forward-backward algorithm as differentiation of the backward algorithm
  Makefile
  examples/forward_backward.py
Labels: awaiting response, examples

#478 Bump Pyro and PyTorch dependencies and reinstate VAE
  .github/workflows/ci.yml
  Makefile
  examples/vae.py
  setup.py
Labels: WIP, testing

#479 Update uses of obsolete interpretation()
  examples/eeg_slds.py
  examples/minipyro.py
  examples/slds.py
  examples/vae.py
Labels: awaiting review, easy, refactor

#480 Fix make_funsor factory and add a FUNSOR_TYPECHECK interpreter
  funsor/factory.py
  funsor/interpretations.py
  funsor/interpreter.py
  test/test_factory.py
Labels: awaiting review

#483 Clean up examples and tests after black
  examples/eeg_slds.py
  examples/forward_backward.py
  test/test_tensor.py
Labels: awaiting review, easy, refactor

#484 Unexpand short expressions with black
  funsor/adjoint.py
  funsor/distribution.py
  funsor/interpreter.py
  funsor/jax/ops.py
  funsor/joint.py
  funsor/sum_product.py
  funsor/syntax.py
  test/examples/test_bart.py
  test/pyro/test_hmm.py
  test/test_approximations.py
  test/test_distribution.py
  test/test_elbo.py
  test/test_gaussian.py
  test/test_minipyro.py
  test/test_optimizer.py
  test/test_samplers.py
  test/test_sum_product.py
  test/test_tensor.py
  test/test_terms.py
  test/test_typing.py
Labels: awaiting review, discussion

#488 Use Approximate in adjoint
  funsor/adjoint.py
  funsor/approximations.py
  funsor/delta.py
  funsor/factory.py
  funsor/jax/ops.py
  funsor/testing.py
  setup.cfg
  test/test_approximations.py
Labels: awaiting review

#495 Extract A-normal form computation from stack_reinterpret
  funsor/cnf.py
  funsor/interpreter.py
Labels: awaiting review

#491 Refactor ops to allow non-funsor parameters
  .github/workflows/ci.yml
  funsor/adjoint.py
  funsor/affine.py
  funsor/cnf.py
  funsor/distribution.py
  funsor/domains.py
  funsor/einsum/numpy_log.py
  funsor/gaussian.py
  funsor/jax/distributions.py
  funsor/jax/ops.py
  funsor/joint.py
  funsor/ops/array.py
  funsor/ops/builtin.py
  funsor/ops/op.py
  funsor/optimizer.py
  funsor/registry.py
  funsor/tensor.py
  funsor/terms.py
  funsor/testing.py
  funsor/torch/distributions.py
  funsor/torch/ops.py
  funsor/util.py
  test/examples/test_bart.py
  test/examples/test_sensor_fusion.py
  test/test_distribution.py
  test/test_distribution_generic.py
  test/test_ops.py
  test/test_samplers.py
  test/test_tensor.py
Labels: awaiting review, refactor

#498 Replace null -> ops.null in a few places
  funsor/adjoint.py
  funsor/cnf.py
  funsor/optimizer.py
Labels: awaiting review, easy, refactor

#490 Support ops.sum(data, dim=None, keepdims=False)
  funsor/domains.py
  funsor/jax/ops.py
  funsor/ops/array.py
  funsor/tensor.py
  funsor/torch/ops.py
  test/test_tensor.py
Labels: awaiting review, enhancement

#500 Try to use canonical dtype as much as possible in JAX backend
  .github/workflows/ci.yml
  funsor/jax/ops.py
  test/test_samplers.py
  test/test_tensor.py
Labels: awaiting review

#499 Share more code between reinterpret implementations
  funsor/cnf.py
  funsor/interpreter.py
  funsor/jax/__init__.py
  funsor/terms.py
  funsor/torch/__init__.py
Labels: awaiting review, refactor

#504 Add a generic op factory make_op
  funsor/__init__.py
  funsor/domains.py
  funsor/op_factory.py
  funsor/terms.py
  funsor/typing.py
  test/test_op_factory.py
  test/test_terms.py
Labels: awaiting review, enhancement

#482 Add ReductionOp, ops.mean, ops.std, ops.var
  funsor/affine.py
  funsor/domains.py
  funsor/jax/ops.py
  funsor/ops/array.py
  funsor/ops/op.py
  funsor/tensor.py
  funsor/terms.py
  funsor/torch/ops.py
  test/test_tensor.py
  test/test_terms.py
Labels: awaiting review, enhancement

#505 Use new ops to reduce multiple dims in eager_reduce
  funsor/tensor.py
Labels: awaiting review

#506 Allow stack Numbers
  funsor/ops/array.py
  funsor/tensor.py
  funsor/terms.py
  test/test_tensor.py
Labels: awaiting review

#507 Support nn.Modules in @function, make_funsor, and make_op
  examples/forward_backward.py
  examples/vae.py
  funsor/factory.py
  funsor/op_factory.py
  funsor/ops/op.py
  funsor/tensor.py
  funsor/util.py
  test/examples/test_bart.py
  test/test_factory.py
  test/test_op_factory.py
Labels: awaiting review, enhancement

#508 Fix Independent() distribution conversion
  funsor/distribution.py
  test/test_distribution_generic.py
Labels: awaiting review, bug, easy

#511 Fix printing of Tensors
  funsor/domains.py
  funsor/tensor.py
  test/test_domains.py
  test/test_tensor.py
Labels: awaiting review, easy

#509 Named tensor notation tutorial Part 1
  tutorials/named_tensor_notation_i.ipynb
Labels: awaiting review, examples

#513 Add named_tensor_notation_i tutorial to index file
  docs/source/index.rst
  tutorials/named_tensor_notation_i.ipynb
Labels: awaiting review, easy
