Repository pyro-ppl/funsor, pull requests merged in 2021-04, with the labels that each got.

#514 Add forward-backward example to index file
  docs/source/index.rst
Labels: awaiting review, easy

#515 Remove github_url link when render tutorial
  docs/Makefile
  docs/requirements.txt
  tutorials/named_tensor_notation_i.ipynb
Labels: awaiting review

#516 Adam interpretation
  Makefile
  docs/source/index.rst
  examples/adam.py
  funsor/__init__.py
  funsor/adam.py
  test/test_import.py
Labels: awaiting review, enhancement, examples

#519 Reshape using Variable in Named Tensor tutorial Part 1
  tutorials/named_tensor_notation_i.ipynb
Labels: awaiting review

#517 Fix a scatter eager_subs issue
  funsor/terms.py
  test/test_tensor.py
Labels: awaiting review

#520 Talbot's method for numerical inversion of the Laplace transform
  Makefile
  docs/source/index.rst
  examples/talbot.py
  funsor/adam.py
  funsor/torch/ops.py
Labels: awaiting review, examples

#523 Reimplement substitute() using anf()
  funsor/interpreter.py
  funsor/pyro/distribution.py
  funsor/terms.py
  test/examples/test_bart.py
Labels: awaiting review, refactor

#527 Clarify meaning of reduced_vars in Scatter docs
  funsor/terms.py
Labels: awaiting review, easy

#530 Add docs for Delta
  funsor/delta.py
Labels: awaiting review, easy
